### ISSUE TITLE
[Bug] Funktion WC_PensoPay_Helper::price_normalize bliver kaldt forkert

### ISSUE THREAD

**Issue by rasmus0201** [pensopay/woocommerce-pensopay#1]
https://github.com/PensoPay/woocommerce-pensopay/blob/3eae7144a1988871562d0a5d0bdbae63bab9cf18/woocommerce-pensopay.php#L1236

Stacktrace:

```
[16-Oct-2021 21:21:00 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WC_PensoPay_Helper::price_normalize(), 1 passed in /wp-content/plugins/woo-pensopay/woocommerce-pensopay.php on line 1236 and exactly 2 expected in /wp-content/plugins/woo-pensopay/classes/woocommerce-pensopay-helper.php:93
Stack trace:
#0 /wp-content/plugins/woo-pensopay/woocommerce-pensopay.php(1236): WC_PensoPay_Helper::price_normalize(27000)
#1 /wp-includes/class-wp-hook.php(303): WC_PensoPay->callback_handler('')
#2 /wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#3 /wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#4 /wp-content/plugins/woocommerce/includes/class-wc-api.php(161): do_action('woocommerce_api...')
#5 /wp-includes/class-wp-hook.php(303): WC_API->handle_ in /wp-content/plugins/woo-pensopay/classes/woocommerce-pensopay-helper.php on line 93
```

Fix:

Ser ud til parentesen er sat forkert det burde være (har også slettet det ekstra format `%s` da det ikke behøves længere) - medmindre det er meningen den stadig skal være der?:
```php 
$order->note( sprintf( __( 'Refunded %s', 'woo-pensopay' ), WC_PensoPay_Helper::price_normalize( $transaction->amount, $json->currency ) ) );
```

**Comment by idmistir** [comment]
Fixed in 7.1.4, thank you for reporting.
